from __future__ import annotations

from pathlib import Path
import csv
import io
import re
import urllib.request

SOURCE_COMMIT = "b5ff7d0d26df0863b9b6c5e8f946961ea9fef1f3"
BASE_URL = (
    "https://raw.githubusercontent.com/kapzam123/subtitle-frequency/"
    f"{SOURCE_COMMIT}/top_words"
)
SOURCE_RANK_LIMIT = 30_000

EN_TO_RU = dict(
    zip(
        "qwertyuiop[]asdfghjkl;'zxcvbnm,.",
        "йцукенгшщзхъфывапролджэячсмитьбю",
    )
)
EN_TO_RU["`"] = "ё"
RU_TO_EN = {value: key for key, value in EN_TO_RU.items()}


def download(language: str) -> str:
    url = f"{BASE_URL}/{language}_top_words.csv"
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8-sig")


def clean_word(language: str, value: str) -> str | None:
    value = value.strip().lower()
    if language == "ru":
        value = value.replace("ё", "е")
        return value if re.fullmatch(r"[а-я]+", value) and len(value) >= 3 else None
    return value if re.fullmatch(r"[a-z]+", value) and len(value) >= 3 else None


def load(language: str) -> tuple[dict[str, tuple[int, int]], int]:
    rows = list(csv.DictReader(io.StringIO(download(language))))
    forms: dict[str, tuple[int, int]] = {}
    for raw_rank, row in enumerate(rows, start=1):
        word = clean_word(language, row["word"])
        if word is None:
            continue
        count = int(row["count"])
        if word in forms:
            old_rank, old_count = forms[word]
            forms[word] = (min(old_rank, raw_rank), old_count + count)
        else:
            forms[word] = (raw_rank, count)
    return forms, len(rows)


def target_rank_limit(word: str) -> int:
    length = len(word)
    if length == 3:
        return 0
    if length == 4:
        return 10_000
    return 15_000


def target_eligible(word: str, rank: int) -> bool:
    return rank <= target_rank_limit(word)


def wrong_layout(language: str, word: str) -> str:
    table = RU_TO_EN if language == "ru" else EN_TO_RU
    return "".join(table.get(char, char) for char in word)


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(
            f"{path}: expected one match, got {count}: {old[:120]!r}"
        )
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


def render_table(name: str, forms: dict[str, tuple[int, int]]) -> str:
    lines = [f"pub const {name}: &[(&str, u16)] = &["]
    for word, (rank, _count) in sorted(forms.items()):
        lines.append(f'    ("{word}", {rank}),')
    lines.append("];")
    return "\n".join(lines)


def generate_rust_module(
    ru_source: dict[str, tuple[int, int]],
    en_source: dict[str, tuple[int, int]],
) -> str:
    return f'''// @generated by tools/generate_frequency_lexicon.py for G-switcher 1.0.10.
// Source: OpenSubtitles2018 word-form frequencies mirrored at
// https://github.com/kapzam123/subtitle-frequency, pinned to {SOURCE_COMMIT}.
// Original frequency data: CC BY 3.0. See THIRD_PARTY_DATA.md.
//
// Generated runtime frequency evidence starts at 4 letters; 3-letter forms
// remain under the existing context-sensitive detector policy. Source protection
// keeps 4+ letter forms from the first 30,000 corpus rows per language. Target
// promotion is <= 10,000 for 4-letter forms and <= 15,000 for 5+ letters.

use crate::model::Language;

{render_table("RU_FORMS", ru_source)}

{render_table("EN_FORMS", en_source)}

pub fn forms(language: Language) -> &'static [(&'static str, u16)] {{
    match language {{
        Language::Russian => RU_FORMS,
        Language::English => EN_FORMS,
    }}
}}

pub fn rank(language: Language, token: &str) -> Option<u16> {{
    let table = forms(language);
    table
        .binary_search_by(|(word, _)| (*word).cmp(token))
        .ok()
        .map(|index| table[index].1)
}}

pub fn target_eligible(word: &str, rank: u16) -> bool {{
    let limit = match word.chars().count() {{
        0..=2 => 0,
        3 => 0,
        4 => 10_000,
        _ => 15_000,
    }};
    rank <= limit
}}

pub fn target_word_score(language: Language, token: &str) -> i32 {{
    rank(language, token)
        .filter(|rank| target_eligible(token, *rank))
        .map(|_| 15)
        .unwrap_or(0)
}}

pub fn source_word_score(language: Language, token: &str) -> i32 {{
    rank(language, token).map(|_| 15).unwrap_or(0)
}}

pub fn has_target_prefix(language: Language, prefix: &str) -> bool {{
    if prefix.chars().count() < 4 {{
        return false;
    }}
    let table = forms(language);
    let start = table.partition_point(|(word, _)| *word < prefix);
    table[start..]
        .iter()
        .take_while(|(word, _)| word.starts_with(prefix))
        .any(|(word, rank)| target_eligible(word, *rank) && word.len() > prefix.len())
}}
'''


def patch_runtime() -> None:
    replace_once(
        "src/lib.rs",
        "pub mod detector;\npub mod frequency_model;",
        "pub mod detector;\nmod frequent_forms;\npub mod frequency_model;",
    )
    replace_once(
        "src/frequency_model.rs",
        "use crate::model::Language;",
        "use crate::{frequent_forms, model::Language};",
    )

    old_score = '''pub fn word_score(language: Language, token: &str) -> i32 {
    let (top, common) = match language {
        Language::English => (EN_TOP, EN_COMMON),
        Language::Russian => (RU_TOP, RU_COMMON),
    };

    if let Some(index) = words(top).position(|word| word == token) {
        return match index {
            0..=19 => 26,
            20..=49 => 23,
            50..=79 => 20,
            _ => 17,
        };
    }
    if contains_word(common, token) {
        return 15;
    }
    0
}
'''
    new_score = '''pub fn word_score(language: Language, token: &str) -> i32 {
    let curated = curated_word_score(language, token);
    if curated > 0 {
        return curated;
    }
    frequent_forms::target_word_score(language, token)
}

pub fn source_word_score(language: Language, token: &str) -> i32 {
    let curated = curated_word_score(language, token);
    if curated > 0 {
        return curated;
    }
    frequent_forms::source_word_score(language, token)
}

fn curated_word_score(language: Language, token: &str) -> i32 {
    let (top, common) = match language {
        Language::English => (EN_TOP, EN_COMMON),
        Language::Russian => (RU_TOP, RU_COMMON),
    };

    if let Some(index) = words(top).position(|word| word == token) {
        return match index {
            0..=19 => 26,
            20..=49 => 23,
            50..=79 => 20,
            _ => 17,
        };
    }
    if contains_word(common, token) {
        return 15;
    }
    0
}
'''
    replace_once("src/frequency_model.rs", old_score, new_score)

    old_prefix = '''    words(top)
        .chain(words(common))
        .any(|word| word.starts_with(token) && word.len() > token.len())
}'''
    new_prefix = '''    words(top)
        .chain(words(common))
        .any(|word| word.starts_with(token) && word.len() > token.len())
        || frequent_forms::has_target_prefix(language, token)
}'''
    replace_once("src/frequency_model.rs", old_prefix, new_prefix)

    replace_once(
        "src/detector.rs",
        "let source_frequency = frequency_model::word_score(source, &normalized);",
        "let source_frequency = frequency_model::source_word_score(source, &normalized);",
    )


def patch_tests() -> None:
    detector_anchor = '''    #[test]\n    fn corrects_known_wrong_layout_words() {'''
    detector_test = '''    #[test]\n    fn generated_frequent_forms_are_source_safe_and_target_covered() {\n        let mut protected_sources = 0usize;\n        let mut promoted_targets = 0usize;\n        let mut intentional_collisions = 0usize;\n        let mut code_safe_skips = 0usize;\n\n        for target in [Language::Russian, Language::English] {\n            for &(word, rank) in crate::frequent_forms::forms(target) {\n                assert!(\n                    frequency_model::source_word_score(target, word) >= 15,\n                    "frequent source form is not protected: {word}"\n                );\n                protected_sources += 1;\n\n                if !crate::frequent_forms::target_eligible(word, rank) {\n                    continue;\n                }\n\n                let wrong = opposite_layout_text(word, target);\n                if is_code_safe_token(&wrong) {\n                    code_safe_skips += 1;\n                    continue;\n                }\n\n                let source = opposite(target);\n                let normalized_source = normalize(&wrong, source);\n                if frequency_model::source_word_score(source, &normalized_source) >= 15 {\n                    intentional_collisions += 1;\n                    assert!(\n                        correction_at_boundary_with_context(\n                            &wrong,\n                            &[],\n                            DEFAULT_CONFIDENCE_THRESHOLD,\n                            &[],\n                        )\n                        .is_none(),\n                        "frequent cross-language source collision must stay fail-open: {wrong} -> {word}"\n                    );\n                    continue;\n                }\n\n                let detection = correction_at_boundary_with_context(\n                    &wrong,\n                    &[],\n                    DEFAULT_CONFIDENCE_THRESHOLD,\n                    &[],\n                )\n                .unwrap_or_else(|| panic!("frequent target form was not corrected: {wrong} -> {word}"));\n                assert_eq!(detection.target, target);\n                assert_eq!(normalize(&detection.corrected, target), word);\n                assert_eq!(detection.confidence, 100);\n                promoted_targets += 1;\n            }\n        }\n\n        assert!(protected_sources > 40_000);\n        assert!(promoted_targets > 15_000);\n        eprintln!(\n            "frequency lexicon: protected_sources={protected_sources}, promoted_targets={promoted_targets}, intentional_collisions={intentional_collisions}, code_safe_skips={code_safe_skips}"\n        );\n    }\n\n    #[test]\n    fn common_frequency_wordforms_are_deterministic() {\n        for (word, language) in [\n            ("мама", Language::Russian),\n            ("мыла", Language::Russian),\n            ("раму", Language::Russian),\n            ("знаешь", Language::Russian),\n            ("хочешь", Language::Russian),\n            ("сказала", Language::Russian),\n            ("домой", Language::Russian),\n            ("wanted", Language::English),\n            ("looking", Language::English),\n            ("friends", Language::English),\n            ("mother", Language::English),\n        ] {\n            assert!(\n                frequency_model::word_score(language, word) >= 15,\n                "missing frequent form: {word}"\n            );\n            let wrong = opposite_layout_text(word, language);\n            let source = opposite(language);\n            let normalized_source = normalize(&wrong, source);\n            if frequency_model::source_word_score(source, &normalized_source) >= 15 {\n                continue;\n            }\n            let detection = correction_at_boundary_with_context(\n                &wrong,\n                &[],\n                DEFAULT_CONFIDENCE_THRESHOLD,\n                &[],\n            )\n            .unwrap_or_else(|| panic!("frequent form did not restore: {wrong} -> {word}"));\n            assert_eq!(normalize(&detection.corrected, language), word);\n        }\n    }\n\n    #[test]\n    fn corrects_known_wrong_layout_words() {'''
    replace_once("src/detector.rs", detector_anchor, detector_test)

    e2e_anchor = '''    eprintln!("G-switcher E2E checkpoint: boundary prefix completion");'''
    e2e_test = '''    eprintln!("G-switcher E2E checkpoint: frequent everyday wordforms");\n    run_case(\n        window,\n        edit,\n        ui_thread_id,\n        Language::English,\n        &keys(b"PYFTIM "),\n        "знаешь ",\n    );\n    run_case(\n        window,\n        edit,\n        ui_thread_id,\n        Language::English,\n        &keys(b"LJVJQ "),\n        "домой ",\n    );\n    run_case(\n        window,\n        edit,\n        ui_thread_id,\n        Language::English,\n        &keys(b"VFIBYF "),\n        "машина ",\n    );\n    run_case(\n        window,\n        edit,\n        ui_thread_id,\n        Language::Russian,\n        &keys(b"WANTED "),\n        "wanted ",\n    );\n    run_case(\n        window,\n        edit,\n        ui_thread_id,\n        Language::Russian,\n        &keys(b"LOOKING "),\n        "looking ",\n    );\n\n    eprintln!("G-switcher E2E checkpoint: boundary prefix completion");'''
    replace_once("src/windows_runtime/e2e_tests.rs", e2e_anchor, e2e_test)


def write_docs(
    ru: dict[str, tuple[int, int]],
    en: dict[str, tuple[int, int]],
    ru_rows: int,
    en_rows: int,
    ru_source: dict[str, tuple[int, int]],
    en_source: dict[str, tuple[int, int]],
) -> None:
    def promoted(source: dict[str, tuple[int, int]]) -> dict[str, tuple[int, int]]:
        return {
            word: data
            for word, data in source.items()
            if target_eligible(word, data[0])
        }

    ru_promoted = promoted(ru_source)
    en_promoted = promoted(en_source)

    def token_mass(forms: dict[str, tuple[int, int]]) -> int:
        return sum(count for _rank, count in forms.values())

    def pct(part: int, whole: int) -> float:
        return 100.0 * part / whole if whole else 0.0

    def collisions(
        language: str,
        target_forms: dict[str, tuple[int, int]],
        other_source: dict[str, tuple[int, int]],
    ) -> list[tuple[int, str, str, int]]:
        result: list[tuple[int, str, str, int]] = []
        other_language = "en" if language == "ru" else "ru"
        for word, (rank, _count) in target_forms.items():
            wrong = wrong_layout(language, word)
            normalized = clean_word(other_language, wrong)
            if normalized and normalized in other_source:
                result.append((rank, word, wrong, other_source[normalized][0]))
        return sorted(result)

    ru_collisions = collisions("ru", ru_promoted, en_source)
    en_collisions = collisions("en", en_promoted, ru_source)

    probes_ru = [
        "мама",
        "мыла",
        "раму",
        "знаешь",
        "хочешь",
        "сказала",
        "домой",
        "машина",
        "работу",
        "детей",
    ]
    probes_en = [
        "mother",
        "wanted",
        "looking",
        "friends",
        "home",
        "children",
        "worked",
        "going",
        "please",
        "sorry",
    ]

    def probe_lines(forms: dict[str, tuple[int, int]], words: list[str]) -> str:
        lines = []
        for word in words:
            data = forms.get(word)
            if data:
                lines.append(f"- `{word}`: raw rank {data[0]:,}")
            else:
                lines.append(f"- `{word}`: not present in pinned top-30k")
        return "\n".join(lines)

    collision_preview = []
    for rank, word, wrong, other_rank in ru_collisions[:20]:
        collision_preview.append(
            f"- RU `{word}` ↔ EN source `{wrong}` "
            f"(RU rank {rank}, EN rank {other_rank})"
        )
    for rank, word, wrong, other_rank in en_collisions[:20]:
        collision_preview.append(
            f"- EN `{word}` ↔ RU source `{wrong}` "
            f"(EN rank {rank}, RU rank {other_rank})"
        )

    ru_clean_mass = token_mass(ru)
    en_clean_mass = token_mass(en)
    ru_source_mass = token_mass(ru_source)
    en_source_mass = token_mass(en_source)
    ru_target_mass = token_mass(ru_promoted)
    en_target_mass = token_mass(en_promoted)

    report = f'''# G-switcher 1.0.10 frequency lexicon audit

Generated from the OpenSubtitles2018 surface-form frequency lists mirrored by `kapzam123/subtitle-frequency`, pinned to commit `{SOURCE_COMMIT}`. The original frequency data is CC BY 3.0.

The runtime tables intentionally use **surface forms**, because G-switcher must recognize what a person actually types (`мама`, `маме`, `маму`, `wanted`, `looking`, etc.), not only dictionary lemmas. OpenCorpora's current downloadable unigram lists and the Lyashevskaya–Sharoff/NKRYa frequency dictionary were reviewed as independent Russian-frequency references during design; their data is not copied into the generated runtime table.

## Selection policy

- Generated runtime frequency evidence starts at 4 letters. Three-letter corpus forms and generated prefixes shorter than 4 letters are deliberately held out so the existing context-sensitive short-word policy remains unchanged.
- Source protection: every normalized alphabetic 4+ letter form whose raw source rank is <= {SOURCE_RANK_LIMIT:,}; this layer is deliberately broad.
- Automatic target promotion: rank <= 10,000 for 4-letter forms and <= 15,000 for 5+ letter forms.
- Precedence is explicit source > curated source > curated target > generated source/target. Generated-vs-generated collisions stay fail-open.
- Russian `ё` is normalized to `е`, matching the detector's existing normalization.
- Tokens shorter than 3 letters and non-alphabetic rows are excluded because automatic correction already ignores them or treats them as special input.
- If a target's physical wrong-layout spelling is itself a frequent source form in the opposite language, source protection wins and the case stays fail-open.
- Global confidence thresholds are unchanged.

## Pinned corpus statistics

| Metric | Russian | English |
| --- | ---: | ---: |
| Raw CSV rows | {ru_rows:,} | {en_rows:,} |
| Clean unique >=3-letter forms | {len(ru):,} | {len(en):,} |
| Embedded source-protection forms | {len(ru_source):,} | {len(en_source):,} |
| Target-promoted forms before collision/code-safe gates | {len(ru_promoted):,} | {len(en_promoted):,} |
| Source-layer token mass within clean pinned list | {pct(ru_source_mass, ru_clean_mass):.4f}% | {pct(en_source_mass, en_clean_mass):.4f}% |
| Target-promotion token mass within clean pinned list | {pct(ru_target_mass, ru_clean_mass):.4f}% | {pct(en_target_mass, en_clean_mass):.4f}% |
| Frequent cross-layout collisions kept fail-open | {len(ru_collisions):,} | {len(en_collisions):,} |

## Everyday probes — Russian

{probe_lines(ru, probes_ru)}

## Everyday probes — English

{probe_lines(en, probes_en)}

## Highest-frequency cross-layout collisions

{chr(10).join(collision_preview) if collision_preview else '- none'}

The exhaustive Rust regression checks every embedded source form for preservation and every promoted target form for deterministic restoration unless it is an explicit frequent-source collision or a protected code-like token. Real Win32 E2E additionally exercises representative RU and EN wordforms through the low-level keyboard hook and `SendInput` path.
'''
    Path("docs/FREQUENCY_LEXICON_1_0_10.md").write_text(report, encoding="utf-8")

    attribution = f'''# Third-party data attribution

## OpenSubtitles2018 word-form frequency data

G-switcher 1.0.10 and the 2.0.0 line based on it include a generated, filtered frequency table derived from the Russian and English word-form frequency lists in `kapzam123/subtitle-frequency`, pinned to commit `{SOURCE_COMMIT}`. That repository mirrors data derived from OpenSubtitles2018.

Original data license: Creative Commons Attribution 3.0 (CC BY 3.0). Source repository: https://github.com/kapzam123/subtitle-frequency . Original project attribution: OpenSubtitles / OpenSubtitles2018.

G-switcher stores only normalized word forms and source ranks needed for local detector decisions. No subtitle text, sentences, raw counts, or network retrieval code is linked into the runtime executable. The generator is a development-time reproducibility tool only.
'''
    Path("THIRD_PARTY_DATA.md").write_text(attribution, encoding="utf-8")


def main() -> None:
    ru, ru_rows = load("ru")
    en, en_rows = load("en")
    ru_source = {
        word: data
        for word, data in ru.items()
        if data[0] <= SOURCE_RANK_LIMIT and len(word) >= 4
    }
    en_source = {
        word: data
        for word, data in en.items()
        if data[0] <= SOURCE_RANK_LIMIT and len(word) >= 4
    }

    Path("src/frequent_forms.rs").write_text(
        generate_rust_module(ru_source, en_source), encoding="utf-8"
    )
    if "mod frequent_forms;" not in Path("src/lib.rs").read_text(encoding="utf-8"):
        patch_runtime()
        patch_tests()
    write_docs(ru, en, ru_rows, en_rows, ru_source, en_source)

    print(f"Russian embedded source forms: {len(ru_source):,}")
    print(f"English embedded source forms: {len(en_source):,}")


if __name__ == "__main__":
    main()
